version: 0.2
env:
  variables:
    APP_NAME: "personal-website"
phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - ng build --configuration=production
  post_build:
    commands:
      - cd dist/personal-website
      - aws s3 sync . s3://jackwhurt.com --delete